---
logging:
  level:
    org.springframework: INFO
    io.liquidsoftware: DEBUG

spring:
  reactor:
    context-propagation: auto
  web:
    error:
      include-message: always

common:
  mode: dev

  mongodb:
    database: modulith-mongo
    uri: mongodb://localhost:27017/

  jackson:
#    deserialization.UNWRAP_ROOT_VALUE: true

  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss

  threads:
    virtual:
      enabled: true

security:
  jwt:
    token:
      secretKey: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
      validityInMs: 3600000 # 1 HOUR
